version: '3.3'

networks:
  mynet:
    driver: bridge

volumes:
  data:

services:

  database:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - mynet
    container_name: maria_db
    hostname: database
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: database
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  webapp:
    build: .
    ports:
      - 8080:8080
    networks:
      - mynet
    restart: always
    container_name: webapp
    hostname: webservice
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
